FROM***REMOVED***alpine:3.20

WORKDIR***REMOVED***/www

COPY***REMOVED***package.json***REMOVED***/www/package.json

RUN***REMOVED***apk***REMOVED***add***REMOVED***--update***REMOVED***nodejs***REMOVED***npm

RUN***REMOVED***npm***REMOVED***install

COPY***REMOVED***.***REMOVED***/www/

EXPOSE***REMOVED***3000

CMD***REMOVED***["npm",***REMOVED***"start"]



