FROM***REMOVED***alpine:3.20

RUN***REMOVED***apk***REMOVED***add***REMOVED***--no-cache***REMOVED***bash***REMOVED***bash-doc***REMOVED***bash-completion
RUN***REMOVED***apk***REMOVED***add***REMOVED***--no-cache***REMOVED***musl-dev***REMOVED***
RUN***REMOVED***apk***REMOVED***add***REMOVED***--no-cache***REMOVED***gfortran***REMOVED***gdb***REMOVED***make

RUN***REMOVED***apk***REMOVED***add***REMOVED***--no-cache***REMOVED***nano