FROM***REMOVED***alpine:3.20

WORKDIR***REMOVED***/api

COPY***REMOVED***package.json***REMOVED***/api/package.json

RUN***REMOVED***apk***REMOVED***add***REMOVED***--update***REMOVED***nodejs***REMOVED***npm

RUN***REMOVED***npm***REMOVED***install***REMOVED***--force

COPY***REMOVED***.***REMOVED***/api/

EXPOSE***REMOVED***3000

CMD***REMOVED***["npm",***REMOVED***"start"]



